version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootCatho
      MYSQL_DATABASE: bibliotheque
      MYSQL_USER: biblioUser
      MYSQL_PASSWORD: mdp123
    ports:
      - 3306:3306
    volumes:
      - ./bdd:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080