server.port: 8081

spring:
  spring:
    security:
      oauth2:
        client:
          provider:
            keycloak:
              token-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/token
              authorization-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/auth
              userinfo-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo
              user-name-attribute: preferred_username
          registration:
            keycloak-with-test-scope:
              provider: keycloak
              client-id: spring-with-test-scope
              client-secret: c6480137-1526-4c3e-aed3-295aabcb7609
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            keycloak-without-test-scope:
              provider: keycloak
              client-id: spring-without-test-scope
              client-secret: f6fc369d-49ce-4132-8282-5b5d413eba23
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      routes:
        - id: bookModule
          uri: http://localhost:9010/
          predicates:
            - Path=/api/book/**
        - id: commentModule
          uri: http://localhost:9020/
          predicates:
            - Path=/api/comment/**
        - id: customerModule
          uri: http://localhost:9030/
          predicates:
            - Path=/api/customer/**


  application:
    name: gateway-app
  boot:
    admin:
      client:
          url: http://localhost:9000

management.endpoints.web.exposure.include: health
