server.port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: bookModule
          uri: http://localhost:9010/
          predicates:
            - Path=/api/book/**
        - id: commentModule
          uri: http://localhost:9020/
          predicates:
            - Path=/api/comment/**
        - id: customerModule
          uri: http://localhost:9030/
          predicates:
            - Path=/api/customer/**


  application:
    name: gateway-app
  boot:
    admin:
      client:
          url: http://localhost:9000

management.endpoints.web.exposure.include: health
